// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_store_RazorPages.Data;

#nullable disable

namespace Test_store_RazorPages.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918063946_addCategoryToDb")]
    partial class addCategoryToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test_store_RazorPages.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action movies",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comedy movies",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Drama movies",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Horror movies",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Romance movies",
                            Name = "Romance"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
